### ISSUE TITLE
[Bug]: Carrier::fromJson() error with code installed into a Laravel 10 app (does include the Twilio SDK for other uses)

### ISSUE THREAD

**Issue by KS-Verbosity** [codebar-ag/laravel-twilio-verify#5]
### What happened?

CodebarAg\TwilioVerify\DTO\Carrier::fromJson(): Argument #1 ($data) must be of type array, null given, called in /Users/keithstreeter/Laravel/comms/vendor/codebar-ag/laravel-twilio-verify/src/DTO/Lookup.php on line 10.

Error happens on $verificationStart = TwilioVerify::start(to: '+1XXXYYYZZZZ');

The SMS goes through via a Twilio Verify service that I created, the correct header shows.
Your Device Registration verification code is: 588187. Don't share this code with anyone; our employees will never ask for the code. 

I get the same result running the code from MacOS/Herd Pro and on a Forge Server.
Thank you.

### Package Version

Latest

### PHP Version

8.3

### Laravel Version

10.42

### Which operating systems does with happen with?

macOS

**Comment by StanBarrows** [comment]
hey @KS-Verbosity 

We've updated the package to allow this data nullable, can you check again with [v2.1](https://github.com/codebar-ag/laravel-twilio-verify/releases/tag/v2.1)?

**Comment by KS-Verbosity** [comment]
Hi,

Yes, I will check again to verify. Thank you for all of your help.

Keith

**Comment by KS-Verbosity** [comment]
I can confirm that my code is running without any errors.

Thank you so much!

Keith
